import 'dotenv/config';
import crypto from 'node:crypto'; import fs from 'node:fs'; import path from 'node:path';
import express from 'express'; import helmet from 'helmet'; import morgan from 'morgan'; import multer from 'multer'; import jwt from 'jsonwebtoken';
import swaggerUi from 'swagger-ui-express';
import { openDatabase } from './db.js'; import { compareVersions } from './version.js';
import { getReleasePolicy, normalizeFutureDeadline } from './release.js';
import { openApiDocument } from './openapi.js';
import { CHANNELS, canAccess, ensureInitialAdmin, hashPassword, userScopes, verifyPassword } from './auth.js';
const app=express(), port=Number(process.env.PORT||3333);
const db=openDatabase(path.resolve(process.env.DATABASE_PATH||'./data/updater.db'));
ensureInitialAdmin(db,process.env.ADMIN_USER,process.env.ADMIN_PASSWORD);
const packagesPath=path.resolve(process.env.PACKAGES_PATH||'./packages'), downloadBase=String(process.env.DOWNLOAD_BASE_URL||'').replace(/\/$/,'');
fs.mkdirSync(packagesPath,{recursive:true}); fs.mkdirSync(path.join(packagesPath,'.temp'),{recursive:true});
const upload=multer({dest:path.join(packagesPath,'.temp'),limits:{fileSize:1024*1024*1024}});
app.set('trust proxy',Number(process.env.TRUST_PROXY||1)); app.use(helmet()); app.use(express.json({limit:'512kb'})); app.use(morgan('combined'));
// No desenvolvimento o Next encaminha /downloads para esta rota. Em producao,
// o Nginx pode continuar servindo a mesma pasta diretamente.
app.use('/downloads',express.static(packagesPath,{fallthrough:false,index:false}));
app.get('/api-docs.json',(_q,res)=>res.json(openApiDocument));
app.use('/docs',swaggerUi.serve,swaggerUi.setup(openApiDocument,{customSiteTitle:'Central de Atualização API'}));
const adminAuth=(req,res,next)=>{try{const token=jwt.verify((req.get('authorization')||'').replace(/^Bearer /,''),process.env.JWT_SECRET);const user=db.prepare('SELECT id,username,name,role,active FROM app_user WHERE id=?').get(token.sub);if(!user?.active)throw new Error();req.user=user;req.scopes=userScopes(db,user);next();}catch{res.status(401).json({error:'unauthorized'});}};
const installationAuth=(req,res,next)=>{const value=(req.get('authorization')||'').replace(/^Bearer /,'');if(!process.env.INSTALLATION_KEY||value!==process.env.INSTALLATION_KEY)return res.status(401).json({error:'invalid_installation_key'});next();};
const hashFile=file=>new Promise((resolve,reject)=>{const h=crypto.createHash('sha256');fs.createReadStream(file).on('error',reject).on('data',d=>h.update(d)).on('end',()=>resolve(h.digest('hex')));});
function registerInstallation(body){const{client,terminal,product='pdv',channel='production',currentVersion='0.0.0'}=body;if(!client?.id||!client?.name||!terminal?.id||!terminal?.name)throw new Error('invalid_installation');
 db.prepare(`INSERT INTO client(external_id,name,document) VALUES(?,?,?) ON CONFLICT(external_id) DO UPDATE SET name=excluded.name,document=excluded.document,last_seen_at=CURRENT_TIMESTAMP`).run(client.id,client.name,client.document||null);
 const c=db.prepare('SELECT id FROM client WHERE external_id=?').get(client.id);
 db.prepare(`INSERT INTO terminal(external_id,client_id,name,computer_name,product_code,channel,current_version,os_version) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(external_id) DO UPDATE SET client_id=excluded.client_id,name=excluded.name,computer_name=excluded.computer_name,product_code=excluded.product_code,channel=excluded.channel,current_version=excluded.current_version,os_version=excluded.os_version,last_seen_at=CURRENT_TIMESTAMP`).run(terminal.id,c.id,terminal.name,terminal.computerName||null,product,channel,currentVersion,terminal.osVersion||null);
 return{client:c,terminal:db.prepare('SELECT * FROM terminal WHERE external_id=?').get(terminal.id)};}
app.get('/health',(_q,r)=>r.json({ok:true}));
app.post('/api/v1/auth/login',(req,res)=>{const user=db.prepare('SELECT * FROM app_user WHERE username=?').get(String(req.body?.user||'').trim());if(!user?.active||!verifyPassword(req.body?.password,user.password_hash))return res.status(401).json({error:'invalid_credentials'});res.json({token:jwt.sign({sub:user.id},process.env.JWT_SECRET,{expiresIn:'8h'}),user:{id:user.id,username:user.username,name:user.name,role:user.role}});});
app.get('/api/v1/admin/me',adminAuth,(req,res)=>res.json({...req.user,scopes:req.scopes}));
app.post('/api/v1/updates/check',installationAuth,(req,res)=>{try{const reg=registerInstallation(req.body),{product='pdv',channel='production',currentVersion='0.0.0'}=req.body;
 const releases=db.prepare(`SELECT DISTINCT r.* FROM release r JOIN product p ON p.id=r.product_id JOIN release_target rt ON rt.release_id=r.id WHERE p.code=? AND r.channel=? AND r.active=1 AND r.blocked=0 AND (rt.target_type='all' OR (rt.target_type='client' AND rt.client_id=?)) ORDER BY r.published_at DESC,r.id DESC`).all(product,channel,reg.client.id);
 const release=releases.find(r=>compareVersions(r.version,currentVersion)>0),policy=getReleasePolicy(release),status=release?'update_available':'no_update',message=release?`Versão ${release.version} disponível (${release.artifact_type})${policy.deadlineExpired?' e obrigatória por prazo vencido':''}.`:'Terminal já está atualizado.';
 db.prepare('INSERT INTO terminal_event(terminal_id,release_id,previous_version,target_version,status,message,ip) VALUES(?,?,?,?,?,?,?)').run(reg.terminal.id,release?.id||null,currentVersion,release?.version||null,status,message,req.ip);
 if(!release)return res.json({available:false,currentVersion});res.json({available:true,releaseId:String(release.id),version:release.version,mandatory:policy.mandatory,mandatoryReason:policy.mandatoryReason,deadlineAt:release.deadline_at,deadlineExpired:policy.deadlineExpired,minimumVersion:release.minimum_version,artifactType:release.artifact_type||'package',fileName:release.original_name||path.basename(release.file_path),downloadUrl:`${downloadBase}/${release.file_path}`,sha256:release.sha256,sizeBytes:release.size_bytes,notes:release.notes});}catch(e){res.status(400).json({error:e.message});}});
app.post('/api/v1/updates/events',installationAuth,(req,res)=>{const t=db.prepare('SELECT id FROM terminal WHERE external_id=?').get(req.body.terminalId);if(!t)return res.status(404).json({error:'terminal_not_found'});const release=req.body.targetVersion?db.prepare(`SELECT r.id FROM release r JOIN product p ON p.id=r.product_id WHERE r.version=? AND p.code=? ORDER BY r.id DESC LIMIT 1`).get(req.body.targetVersion,req.body.product||'pdv'):null;db.prepare('INSERT INTO terminal_event(terminal_id,release_id,previous_version,target_version,status,message,ip) VALUES(?,?,?,?,?,?,?)').run(t.id,release?.id||null,req.body.previousVersion||null,req.body.targetVersion||null,req.body.status,req.body.message||null,req.ip);res.status(202).json({accepted:true});});
const allowedProducts=req=>req.scopes.all?db.prepare('SELECT * FROM product ORDER BY name').all():db.prepare('SELECT p.* FROM product p JOIN user_product up ON up.product_id=p.id WHERE up.user_id=? ORDER BY p.name').all(req.user.id);
const allowedProductCodes=req=>allowedProducts(req).map(p=>p.code);
app.get('/api/v1/admin/dashboard',adminAuth,(req,res)=>{const codes=allowedProductCodes(req),codeArgs=req.scopes.all?[]:codes,visible=t=>req.scopes.all?t:codes.length?`${t} WHERE product_code IN (${codes.map(()=>'?').join(',')})`:`${t} WHERE 0`;res.json({clients:db.prepare(`SELECT count(DISTINCT client_id) value FROM (${visible('SELECT client_id,product_code FROM terminal')})`).get(...codeArgs).value,terminals:db.prepare(`SELECT count(*) value FROM (${visible('SELECT id,product_code FROM terminal')})`).get(...codeArgs).value,releases:req.scopes.all?db.prepare('SELECT count(*) value FROM release WHERE active=1').get().value:db.prepare(`SELECT count(*) value FROM release WHERE active=1 AND product_id IN (${req.scopes.productIds.map(()=>'?').join(',')||'NULL'}) AND channel IN (${req.scopes.channels.map(()=>'?').join(',')||'NULL'})`).get(...req.scopes.productIds,...req.scopes.channels).value,errors:0});});
app.get('/api/v1/admin/clients',adminAuth,(req,res)=>{const codes=allowedProductCodes(req);if(!req.scopes.all&&!codes.length)return res.json([]);res.json(db.prepare(`SELECT c.*,count(t.id) terminal_count,max(t.last_seen_at) last_terminal_seen FROM client c JOIN terminal t ON t.client_id=c.id ${req.scopes.all?'':`WHERE t.product_code IN (${codes.map(()=>'?').join(',')})`} GROUP BY c.id ORDER BY c.last_seen_at DESC`).all(...(req.scopes.all?[]:codes)));});
app.get('/api/v1/admin/clients/:id/terminals',adminAuth,(req,res)=>{const codes=allowedProductCodes(req);res.json(req.scopes.all?db.prepare('SELECT * FROM terminal WHERE client_id=? ORDER BY last_seen_at DESC').all(req.params.id):codes.length?db.prepare(`SELECT * FROM terminal WHERE client_id=? AND product_code IN (${codes.map(()=>'?').join(',')}) ORDER BY last_seen_at DESC`).all(req.params.id,...codes):[]);});
app.get('/api/v1/admin/products',adminAuth,(req,res)=>res.json(allowedProducts(req)));
app.post('/api/v1/admin/products',adminAuth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'admin_required'});const r=db.prepare('INSERT INTO product(code,name) VALUES(?,?)').run(req.body.code,req.body.name);res.status(201).json({id:r.lastInsertRowid});});
app.delete('/api/v1/admin/products/:id',adminAuth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'admin_required'});const product=db.prepare('SELECT * FROM product WHERE id=?').get(req.params.id);if(!product)return res.status(404).json({error:'product_not_found'});if(db.prepare('SELECT 1 FROM release WHERE product_id=? LIMIT 1').get(product.id)||db.prepare('SELECT 1 FROM terminal WHERE product_code=? LIMIT 1').get(product.code))return res.status(409).json({error:'product_in_use'});db.prepare('DELETE FROM product WHERE id=?').run(product.id);res.json({deleted:true});});
app.get('/api/v1/admin/releases',adminAuth,(req,res)=>{const {productId,channel}=req.query;let where=[] ,args=[];if(!req.scopes.all){where.push(`r.product_id IN (${req.scopes.productIds.map(()=>'?').join(',')||'NULL'})`,`r.channel IN (${req.scopes.channels.map(()=>'?').join(',')||'NULL'})`);args.push(...req.scopes.productIds,...req.scopes.channels);}if(productId){where.push('r.product_id=?');args.push(productId);}if(channel){where.push('r.channel=?');args.push(channel);}res.json(db.prepare(`SELECT r.*,p.name product_name,group_concat(CASE WHEN rt.target_type='all' THEN 'Todos' ELSE c.name END,', ') targets FROM release r JOIN product p ON p.id=r.product_id JOIN release_target rt ON rt.release_id=r.id LEFT JOIN client c ON c.id=rt.client_id ${where.length?'WHERE '+where.join(' AND '):''} GROUP BY r.id ORDER BY r.published_at DESC`).all(...args));});
app.get('/api/v1/admin/logs',adminAuth,(req,res)=>{const limit=Math.min(Math.max(Number(req.query.limit)||100,1),500),ids=req.scopes.productIds;res.json(db.prepare(`SELECT e.id,e.status,e.message,e.previous_version,e.target_version,e.ip,e.created_at,t.name terminal_name,t.computer_name,c.name client_name,r.artifact_type,p.name product_name FROM terminal_event e LEFT JOIN terminal t ON t.id=e.terminal_id LEFT JOIN client c ON c.id=t.client_id LEFT JOIN release r ON r.id=e.release_id LEFT JOIN product p ON p.id=r.product_id ${req.scopes.all?'':`WHERE (r.product_id IN (${ids.map(()=>'?').join(',')||'NULL'}) OR t.product_code IN (SELECT code FROM product WHERE id IN (${ids.map(()=>'?').join(',')||'NULL'})))`} ORDER BY e.created_at DESC,e.id DESC LIMIT ?`).all(...(req.scopes.all?[]:[...ids,...ids]),limit));});
app.get('/api/v1/admin/users',adminAuth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'admin_required'});res.json(db.prepare(`SELECT u.id,u.username,u.name,u.role,u.active,u.created_at,group_concat(DISTINCT p.name) products,group_concat(DISTINCT uc.channel) channels FROM app_user u LEFT JOIN user_product up ON up.user_id=u.id LEFT JOIN product p ON p.id=up.product_id LEFT JOIN user_channel uc ON uc.user_id=u.id GROUP BY u.id ORDER BY u.name`).all());});
app.post('/api/v1/admin/users',adminAuth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'admin_required'});const role=req.body.role==='admin'?'admin':'operator',productIds=[...new Set((req.body.productIds||[]).map(Number))],channels=[...new Set(req.body.channels||[])];if(role==='operator'&&(!productIds.length||!channels.length))return res.status(400).json({error:'scope_required'});if(channels.some(c=>!CHANNELS.includes(c)))return res.status(400).json({error:'invalid_channel'});const id=db.transaction(()=>{const r=db.prepare('INSERT INTO app_user(username,name,password_hash,role) VALUES(?,?,?,?)').run(String(req.body.username||'').trim(),String(req.body.name||'').trim(),hashPassword(req.body.password),role);for(const productId of productIds)db.prepare('INSERT INTO user_product(user_id,product_id) VALUES(?,?)').run(r.lastInsertRowid,productId);for(const channel of channels)db.prepare('INSERT INTO user_channel(user_id,channel) VALUES(?,?)').run(r.lastInsertRowid,channel);return r.lastInsertRowid;})();res.status(201).json({id});});
app.patch('/api/v1/admin/users/:id',adminAuth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'admin_required'});if(Number(req.params.id)===req.user.id&&req.body.active===false)return res.status(400).json({error:'cannot_disable_self'});db.prepare('UPDATE app_user SET active=? WHERE id=?').run(req.body.active?1:0,req.params.id);res.json({updated:true});});
app.post('/api/v1/admin/releases',adminAuth,upload.fields([{name:'artifact',maxCount:1},{name:'package',maxCount:1}]),async(req,res,next)=>{
 const file=req.files?.artifact?.[0]||req.files?.package?.[0];let final,moved=false;
 try{
  const artifactType=req.body.artifactType==='sql'?'sql':'package',expectedExtension=artifactType==='sql'?'.sql':'.zip',sqlContent=String(req.body.sqlContent||'').trim();
  if(artifactType==='package'&&(!file||path.extname(file.originalname).toLowerCase()!=='.zip'))throw new Error('zip_required');
  if(artifactType==='sql'&&!sqlContent&&(!file||path.extname(file.originalname).toLowerCase()!=='.sql'))throw new Error('sql_required');
  if(!['test','beta','production'].includes(req.body.channel))throw new Error('invalid_channel');
  const product=db.prepare('SELECT * FROM product WHERE id=?').get(req.body.productId);if(!product)throw new Error('product_not_found');
  if(!canAccess(req.scopes,product.id,req.body.channel))return res.status(403).json({error:'scope_denied'});
  const deadlineAt=normalizeFutureDeadline(req.body.deadlineAt);
  const ids=JSON.parse(req.body.targetClientIds||'[]');if(req.body.targetType!=='all'&&!ids.length)throw new Error('target_required');
  const folder=path.join(packagesPath,product.code);fs.mkdirSync(folder,{recursive:true});
  const version=String(req.body.version||'').trim(),safe=version.replace(/[^a-zA-Z0-9._-]/g,'');if(!safe)throw new Error('invalid_version');
  const name=`${safe}-${req.body.channel}${expectedExtension}`;final=path.join(folder,name);if(fs.existsSync(final))throw new Error('release_file_already_exists');
  let originalName,size;
  if(artifactType==='sql'&&sqlContent){fs.writeFileSync(final,sqlContent+'\n','utf8');moved=true;originalName=name;size=fs.statSync(final).size;}
  else{fs.renameSync(file.path,final);moved=true;originalName=file.originalname;size=file.size;}
  const sha=await hashFile(final);
  const run=db.transaction(()=>{const r=db.prepare('INSERT INTO release(product_id,version,channel,file_path,sha256,size_bytes,mandatory,minimum_version,notes,artifact_type,original_name,deadline_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(product.id,version,req.body.channel,`${product.code}/${name}`,sha,size,req.body.mandatory==='true'?1:0,req.body.minimumVersion||null,req.body.notes||null,artifactType,originalName,deadlineAt);if(req.body.targetType==='all')db.prepare("INSERT INTO release_target(release_id,target_type) VALUES(?,'all')").run(r.lastInsertRowid);else for(const id of ids)db.prepare("INSERT INTO release_target(release_id,target_type,client_id) VALUES(?,'client',?)").run(r.lastInsertRowid,id);db.prepare('INSERT INTO terminal_event(release_id,status,message,ip) VALUES(?,?,?,?)').run(r.lastInsertRowid,'published',`Versão ${version} publicada como ${artifactType==='sql'?'script SQL':'pacote de arquivos'}, com prazo até ${deadlineAt}.`,req.ip);return r.lastInsertRowid;});
  res.status(201).json({id:run(),sha256:sha,artifactType,fileName:originalName});
 }catch(e){if(file?.path&&fs.existsSync(file.path))fs.unlinkSync(file.path);if(moved&&final&&fs.existsSync(final))fs.unlinkSync(final);next(e);}
});
app.patch('/api/v1/admin/releases/:id',adminAuth,(req,res)=>{const release=db.prepare('SELECT * FROM release WHERE id=?').get(req.params.id);if(!release)return res.status(404).json({error:'release_not_found'});if(!canAccess(req.scopes,release.product_id,release.channel))return res.status(403).json({error:'scope_denied'});const active=req.body.active===undefined?release.active:(req.body.active?1:0),blocked=req.body.blocked===undefined?release.blocked:(req.body.blocked?1:0);db.prepare('UPDATE release SET active=?,blocked=? WHERE id=?').run(active,blocked,release.id);res.json({updated:true,active:Boolean(active),blocked:Boolean(blocked)});});
app.delete('/api/v1/admin/releases/:id',adminAuth,(req,res)=>{const release=db.prepare(`SELECT r.*,p.code product_code FROM release r JOIN product p ON p.id=r.product_id WHERE r.id=?`).get(req.params.id);if(!release)return res.status(404).json({error:'release_not_found'});if(!canAccess(req.scopes,release.product_id,release.channel))return res.status(403).json({error:'scope_denied'});const installations=db.prepare('SELECT count(*) value FROM terminal WHERE product_code=? AND current_version=?').get(release.product_code,release.version).value;if(installations)return res.status(409).json({error:'release_installed',installations});db.transaction(()=>{db.prepare('UPDATE terminal_event SET release_id=NULL WHERE release_id=?').run(release.id);db.prepare('DELETE FROM release WHERE id=?').run(release.id);})();const shared=db.prepare('SELECT 1 FROM release WHERE file_path=? LIMIT 1').get(release.file_path),artifact=path.resolve(packagesPath,release.file_path);if(!shared&&artifact.startsWith(packagesPath+path.sep)&&fs.existsSync(artifact))fs.unlinkSync(artifact);res.json({deleted:true});});
app.post('/api/v1/admin/releases/:id/copy',adminAuth,(req,res)=>{const source=db.prepare('SELECT * FROM release WHERE id=?').get(req.params.id);if(!source)return res.status(404).json({error:'release_not_found'});const channel=req.body.channel;if(!CHANNELS.includes(channel))return res.status(400).json({error:'invalid_channel'});if(!canAccess(req.scopes,source.product_id,source.channel)||!canAccess(req.scopes,source.product_id,channel))return res.status(403).json({error:'scope_denied'});const ids=(req.body.targetClientIds||[]).map(Number),targetType=req.body.targetType==='client'?'client':'all';if(targetType==='client'&&!ids.length)return res.status(400).json({error:'target_required'});const id=db.transaction(()=>{const r=db.prepare(`INSERT INTO release(product_id,version,channel,file_path,sha256,size_bytes,mandatory,minimum_version,notes,artifact_type,original_name,deadline_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(source.product_id,req.body.version||source.version,channel,source.file_path,source.sha256,source.size_bytes,req.body.mandatory?1:0,req.body.minimumVersion||source.minimum_version,req.body.notes??source.notes,source.artifact_type,source.original_name,normalizeFutureDeadline(req.body.deadlineAt));if(targetType==='all')db.prepare("INSERT INTO release_target(release_id,target_type) VALUES(?,'all')").run(r.lastInsertRowid);else for(const clientId of ids)db.prepare("INSERT INTO release_target(release_id,target_type,client_id) VALUES(?,'client',?)").run(r.lastInsertRowid,clientId);return r.lastInsertRowid;})();res.status(201).json({id});});
app.use((e,_q,res,_n)=>{console.error(e);res.status(400).json({error:e.message||'internal_error'});});app.listen(port,()=>console.log(`Central de Atualização API: ${port}`));
