export const openApiDocument = {
  openapi: '3.0.3',
  info: {
    title: 'Central de Atualização API',
    version: '1.0.0',
    description: 'API para distribuir atualizações, registrar instalações e administrar produtos e releases.'
  },
  servers: [{ url: '/', description: 'Servidor atual' }],
  tags: [
    { name: 'Status' }, { name: 'Autenticação' }, { name: 'Instalações' }, { name: 'Administração' }
  ],
  paths: {
    '/health': { get: { tags: ['Status'], summary: 'Verifica a disponibilidade', responses: { 200: { description: 'API disponível', content: { 'application/json': { schema: { $ref: '#/components/schemas/Health' } } } } } } },
    '/api/v1/auth/login': { post: { tags: ['Autenticação'], summary: 'Autentica um administrador', requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/LoginRequest' } } } }, responses: { 200: { description: 'Login realizado', content: { 'application/json': { schema: { $ref: '#/components/schemas/LoginResponse' } } } }, 401: { $ref: '#/components/responses/Unauthorized' } } } },
    '/api/v1/updates/check': { post: { tags: ['Instalações'], summary: 'Registra a instalação e procura uma atualização', security: [{ InstallationKey: [] }], requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/UpdateCheckRequest' } } } }, responses: { 200: { description: 'Resultado da consulta', content: { 'application/json': { schema: { oneOf: [{ $ref: '#/components/schemas/UpdateAvailable' }, { $ref: '#/components/schemas/UpdateUnavailable' }] } } } }, 400: { $ref: '#/components/responses/BadRequest' }, 401: { $ref: '#/components/responses/Unauthorized' } } } },
    '/api/v1/updates/events': { post: { tags: ['Instalações'], summary: 'Registra um evento da atualização', security: [{ InstallationKey: [] }], requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/UpdateEventRequest' } } } }, responses: { 202: { description: 'Evento aceito', content: { 'application/json': { schema: { type: 'object', properties: { accepted: { type: 'boolean', example: true } } } } } }, 401: { $ref: '#/components/responses/Unauthorized' }, 404: { $ref: '#/components/responses/NotFound' } } } },
    '/api/v1/admin/dashboard': { get: { tags: ['Administração'], summary: 'Obtém os indicadores do painel', security: [{ AdminBearer: [] }], responses: { 200: { description: 'Indicadores', content: { 'application/json': { schema: { $ref: '#/components/schemas/Dashboard' } } } }, 401: { $ref: '#/components/responses/Unauthorized' } } } },
    '/api/v1/admin/clients': { get: { tags: ['Administração'], summary: 'Lista os clientes', security: [{ AdminBearer: [] }], responses: { 200: { description: 'Clientes cadastrados', content: { 'application/json': { schema: { type: 'array', items: { $ref: '#/components/schemas/Client' } } } } }, 401: { $ref: '#/components/responses/Unauthorized' } } } },
    '/api/v1/admin/clients/{id}/terminals': { get: { tags: ['Administração'], summary: 'Lista os terminais de um cliente', security: [{ AdminBearer: [] }], parameters: [{ $ref: '#/components/parameters/Id' }], responses: { 200: { description: 'Terminais do cliente', content: { 'application/json': { schema: { type: 'array', items: { $ref: '#/components/schemas/Terminal' } } } } }, 401: { $ref: '#/components/responses/Unauthorized' } } } },
    '/api/v1/admin/products': {
      get: { tags: ['Administração'], summary: 'Lista os produtos', security: [{ AdminBearer: [] }], responses: { 200: { description: 'Produtos cadastrados', content: { 'application/json': { schema: { type: 'array', items: { $ref: '#/components/schemas/Product' } } } } }, 401: { $ref: '#/components/responses/Unauthorized' } } },
      post: { tags: ['Administração'], summary: 'Cria um produto', security: [{ AdminBearer: [] }], requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/ProductCreate' } } } }, responses: { 201: { description: 'Produto criado', content: { 'application/json': { schema: { $ref: '#/components/schemas/CreatedId' } } } }, 400: { $ref: '#/components/responses/BadRequest' }, 401: { $ref: '#/components/responses/Unauthorized' } } }
    },
    '/api/v1/admin/releases': {
      get: { tags: ['Administração'], summary: 'Lista as releases', security: [{ AdminBearer: [] }], responses: { 200: { description: 'Releases cadastradas', content: { 'application/json': { schema: { type: 'array', items: { $ref: '#/components/schemas/Release' } } } } }, 401: { $ref: '#/components/responses/Unauthorized' } } },
      post: { tags: ['Administração'], summary: 'Publica uma release', security: [{ AdminBearer: [] }], requestBody: { required: true, content: { 'multipart/form-data': { schema: { $ref: '#/components/schemas/ReleaseCreate' } } } }, responses: { 201: { description: 'Release publicada', content: { 'application/json': { schema: { type: 'object', properties: { id: { type: 'integer' }, sha256: { type: 'string' } } } } } }, 400: { $ref: '#/components/responses/BadRequest' }, 401: { $ref: '#/components/responses/Unauthorized' } } }
    },
    '/api/v1/admin/releases/{id}': { patch: { tags: ['Administração'], summary: 'Ativa ou desativa uma release', security: [{ AdminBearer: [] }], parameters: [{ $ref: '#/components/parameters/Id' }], requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['active'], properties: { active: { type: 'boolean' } } } } } }, responses: { 200: { description: 'Release alterada', content: { 'application/json': { schema: { type: 'object', properties: { updated: { type: 'boolean', example: true } } } } } }, 401: { $ref: '#/components/responses/Unauthorized' } } } }
    ,'/api/v1/admin/logs': { get: { tags: ['Administração'], summary: 'Lista o histórico de publicação e atualização', security: [{ AdminBearer: [] }], parameters: [{ name: 'limit', in: 'query', schema: { type: 'integer', default: 100, maximum: 500 } }], responses: { 200: { description: 'Eventos mais recentes', content: { 'application/json': { schema: { type: 'array', items: { $ref: '#/components/schemas/UpdateLog' } } } } }, 401: { $ref: '#/components/responses/Unauthorized' } } } }
  },
  components: {
    securitySchemes: {
      AdminBearer: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT', description: 'Token retornado pelo login administrativo.' },
      InstallationKey: { type: 'http', scheme: 'bearer', description: 'Chave definida em INSTALLATION_KEY.' }
    },
    parameters: { Id: { name: 'id', in: 'path', required: true, schema: { type: 'integer', minimum: 1 } } },
    responses: {
      BadRequest: { description: 'Requisição inválida', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
      Unauthorized: { description: 'Credencial ausente ou inválida', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
      NotFound: { description: 'Registro não encontrado', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } }
    },
    schemas: {
      Health: { type: 'object', required: ['ok'], properties: { ok: { type: 'boolean', example: true } } },
      Error: { type: 'object', required: ['error'], properties: { error: { type: 'string', example: 'unauthorized' } } },
      CreatedId: { type: 'object', properties: { id: { type: 'integer', example: 1 } } },
      LoginRequest: { type: 'object', required: ['user', 'password'], properties: { user: { type: 'string', example: 'admin' }, password: { type: 'string', format: 'password' } } },
      LoginResponse: { type: 'object', properties: { token: { type: 'string', description: 'JWT válido por oito horas.' } } },
      ClientInput: { type: 'object', required: ['id', 'name'], properties: { id: { type: 'string', example: 'uuid-cliente' }, name: { type: 'string', example: 'Cliente Exemplo' }, document: { type: 'string', nullable: true, example: '12345678000190' } } },
      TerminalInput: { type: 'object', required: ['id', 'name'], properties: { id: { type: 'string', example: 'uuid-terminal' }, name: { type: 'string', example: 'CAIXA 01' }, computerName: { type: 'string', nullable: true, example: 'PC-01' }, osVersion: { type: 'string', nullable: true, example: 'Windows 11' } } },
      UpdateCheckRequest: { type: 'object', required: ['client', 'terminal'], properties: { client: { $ref: '#/components/schemas/ClientInput' }, terminal: { $ref: '#/components/schemas/TerminalInput' }, product: { type: 'string', default: 'pdv' }, channel: { type: 'string', enum: ['test', 'beta', 'production'], default: 'production' }, currentVersion: { type: 'string', default: '0.0.0', example: '1.0.0' } } },
      UpdateAvailable: { type: 'object', required: ['available', 'releaseId', 'version', 'artifactType', 'mandatory', 'deadlineAt', 'downloadUrl', 'sha256', 'sizeBytes'], properties: { available: { type: 'boolean', enum: [true] }, releaseId: { type: 'string', description: 'Identificador estável da publicação.' }, version: { type: 'string' }, mandatory: { type: 'boolean', description: 'Verdadeiro quando configurada como obrigatória ou quando o prazo venceu.' }, mandatoryReason: { type: 'string', enum: ['configured', 'deadline'], nullable: true }, deadlineAt: { type: 'string', format: 'date-time', nullable: true }, deadlineExpired: { type: 'boolean' }, minimumVersion: { type: 'string', nullable: true }, artifactType: { type: 'string', enum: ['package', 'sql'] }, fileName: { type: 'string' }, downloadUrl: { type: 'string', format: 'uri' }, sha256: { type: 'string' }, sizeBytes: { type: 'integer' }, notes: { type: 'string', nullable: true } } },
      UpdateUnavailable: { type: 'object', required: ['available', 'currentVersion'], properties: { available: { type: 'boolean', enum: [false] }, currentVersion: { type: 'string' } } },
      UpdateEventRequest: { type: 'object', required: ['terminalId', 'status'], properties: { terminalId: { type: 'string', example: 'uuid-terminal' }, previousVersion: { type: 'string', nullable: true }, targetVersion: { type: 'string', nullable: true }, status: { type: 'string', example: 'installed' }, message: { type: 'string', nullable: true } } },
      Dashboard: { type: 'object', properties: { clients: { type: 'integer' }, terminals: { type: 'integer' }, releases: { type: 'integer' }, errors: { type: 'integer' } } },
      Client: { type: 'object', properties: { id: { type: 'integer' }, external_id: { type: 'string' }, name: { type: 'string' }, document: { type: 'string', nullable: true }, first_seen_at: { type: 'string' }, last_seen_at: { type: 'string' }, terminal_count: { type: 'integer' }, last_terminal_seen: { type: 'string', nullable: true } } },
      Terminal: { type: 'object', properties: { id: { type: 'integer' }, external_id: { type: 'string' }, client_id: { type: 'integer' }, name: { type: 'string' }, computer_name: { type: 'string', nullable: true }, product_code: { type: 'string' }, channel: { type: 'string' }, current_version: { type: 'string' }, os_version: { type: 'string', nullable: true }, first_seen_at: { type: 'string' }, last_seen_at: { type: 'string' } } },
      Product: { type: 'object', properties: { id: { type: 'integer' }, code: { type: 'string' }, name: { type: 'string' }, active: { type: 'integer', enum: [0, 1] }, created_at: { type: 'string' } } },
      ProductCreate: { type: 'object', required: ['code', 'name'], properties: { code: { type: 'string', example: 'pdv' }, name: { type: 'string', example: 'PDV' } } },
      Release: { type: 'object', properties: { id: { type: 'integer' }, product_id: { type: 'integer' }, version: { type: 'string' }, artifact_type: { type: 'string', enum: ['package', 'sql'] }, original_name: { type: 'string' }, channel: { type: 'string' }, file_path: { type: 'string' }, sha256: { type: 'string' }, size_bytes: { type: 'integer' }, mandatory: { type: 'integer', enum: [0, 1] }, deadline_at: { type: 'string', format: 'date-time', nullable: true }, minimum_version: { type: 'string', nullable: true }, notes: { type: 'string', nullable: true }, active: { type: 'integer', enum: [0, 1] }, published_at: { type: 'string' }, product_name: { type: 'string' }, targets: { type: 'string' } } },
      ReleaseCreate: { type: 'object', required: ['artifactType', 'productId', 'version', 'channel', 'targetType', 'deadlineAt'], properties: { artifact: { type: 'string', format: 'binary', description: 'Pacote ZIP obrigatório quando artifactType for package.' }, sqlContent: { type: 'string', description: 'Comandos SQL obrigatórios quando artifactType for sql.' }, artifactType: { type: 'string', enum: ['package', 'sql'] }, productId: { type: 'integer' }, version: { type: 'string', example: '1.2.0' }, channel: { type: 'string', enum: ['test', 'beta', 'production'] }, targetType: { type: 'string', enum: ['all', 'client'] }, targetClientIds: { type: 'string', default: '[]', description: 'Array JSON de IDs quando targetType for client.' }, mandatory: { type: 'boolean', default: false }, deadlineAt: { type: 'string', format: 'date-time', description: 'Prazo após o qual uma atualização opcional passa a ser obrigatória.' }, minimumVersion: { type: 'string', nullable: true }, notes: { type: 'string', nullable: true } } },
      UpdateLog: { type: 'object', properties: { id: { type: 'integer' }, status: { type: 'string' }, message: { type: 'string', nullable: true }, client_name: { type: 'string', nullable: true }, terminal_name: { type: 'string', nullable: true }, product_name: { type: 'string', nullable: true }, previous_version: { type: 'string', nullable: true }, target_version: { type: 'string', nullable: true }, artifact_type: { type: 'string', nullable: true }, ip: { type: 'string', nullable: true }, created_at: { type: 'string' } } }
    }
  }
};
